// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoyBG4_vy74zhaF7q1ibACX3dWkq_aJNA',
    appId: '1:108301171534:web:ea4a1d1f1e5125eeaefc1f',
    messagingSenderId: '108301171534',
    projectId: 'loginpage-v',
    authDomain: 'loginpage-v.firebaseapp.com',
    storageBucket: 'loginpage-v.firebasestorage.app',
    measurementId: 'G-HHTBS2MKYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDioXcYS5SWDKrI3RjbLZXUARjBZQK4c',
    appId: '1:108301171534:android:c81107e7d6ddb51caefc1f',
    messagingSenderId: '108301171534',
    projectId: 'loginpage-v',
    storageBucket: 'loginpage-v.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzW3Deeb-sVtpUrNYPqlVYoxpBD89PUts',
    appId: '1:108301171534:ios:fb49b9557fe0d7b9aefc1f',
    messagingSenderId: '108301171534',
    projectId: 'loginpage-v',
    storageBucket: 'loginpage-v.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzW3Deeb-sVtpUrNYPqlVYoxpBD89PUts',
    appId: '1:108301171534:ios:fb49b9557fe0d7b9aefc1f',
    messagingSenderId: '108301171534',
    projectId: 'loginpage-v',
    storageBucket: 'loginpage-v.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoyBG4_vy74zhaF7q1ibACX3dWkq_aJNA',
    appId: '1:108301171534:web:d5bf773d1ab04daaaefc1f',
    messagingSenderId: '108301171534',
    projectId: 'loginpage-v',
    authDomain: 'loginpage-v.firebaseapp.com',
    storageBucket: 'loginpage-v.firebasestorage.app',
    measurementId: 'G-NZST01G7D5',
  );
}
